(function() {var implementors = {};
implementors["aquamarine"] = [{"text":"impl Unpin for AquamarineBackend","synthetic":true,"types":[]},{"text":"impl Unpin for AquamarineApi","synthetic":true,"types":[]},{"text":"impl Unpin for AwaitedParticle","synthetic":true,"types":[]},{"text":"impl Unpin for AwaitedEffects","synthetic":true,"types":[]},{"text":"impl Unpin for VmPoolConfig","synthetic":true,"types":[]},{"text":"impl Unpin for SendParticle","synthetic":true,"types":[]},{"text":"impl Unpin for StepperEffects","synthetic":true,"types":[]},{"text":"impl Unpin for Plumber","synthetic":true,"types":[]}];
implementors["connection_pool"] = [{"text":"impl Unpin for ConnectionPoolInlet","synthetic":true,"types":[]},{"text":"impl Unpin for ConnectionPoolApi","synthetic":true,"types":[]},{"text":"impl Unpin for ConnectionPoolBehaviour","synthetic":true,"types":[]},{"text":"impl Unpin for Contact","synthetic":true,"types":[]},{"text":"impl Unpin for LifecycleEvent","synthetic":true,"types":[]}];
implementors["fluence_client"] = [{"text":"impl Unpin for Transport","synthetic":true,"types":[]},{"text":"impl Unpin for Client","synthetic":true,"types":[]},{"text":"impl Unpin for ClientCommand","synthetic":true,"types":[]},{"text":"impl Unpin for ClientEvent","synthetic":true,"types":[]}];
implementors["fluence_libp2p"] = [{"text":"impl Unpin for RandomPeerId","synthetic":true,"types":[]}];
implementors["host_closure"] = [{"text":"impl Unpin for Args","synthetic":true,"types":[]},{"text":"impl Unpin for ArgsError","synthetic":true,"types":[]},{"text":"impl Unpin for JError","synthetic":true,"types":[]}];
implementors["kademlia"] = [{"text":"impl Unpin for KademliaApiInlet","synthetic":true,"types":[]},{"text":"impl Unpin for KademliaApi","synthetic":true,"types":[]},{"text":"impl Unpin for KademliaConfig","synthetic":true,"types":[]},{"text":"impl Unpin for Kademlia","synthetic":true,"types":[]},{"text":"impl Unpin for KademliaError","synthetic":true,"types":[]}];
implementors["particle_closures"] = [{"text":"impl&lt;C&gt; Unpin for HostClosures&lt;C&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;C: Unpin,&nbsp;</span>","synthetic":true,"types":[]},{"text":"impl Unpin for NodeInfo","synthetic":true,"types":[]}];
implementors["particle_modules"] = [{"text":"impl Unpin for Blueprint","synthetic":true,"types":[]},{"text":"impl Unpin for ModuleError","synthetic":true,"types":[]}];
implementors["particle_node"] = [{"text":"impl Unpin for Node","synthetic":true,"types":[]},{"text":"impl Unpin for NetworkBehaviour","synthetic":true,"types":[]}];
implementors["particle_protocol"] = [{"text":"impl Unpin for CompletionChannel","synthetic":true,"types":[]},{"text":"impl Unpin for HandlerMessage","synthetic":true,"types":[]},{"text":"impl Unpin for ProtocolConfig","synthetic":true,"types":[]},{"text":"impl Unpin for Particle","synthetic":true,"types":[]}];
implementors["particle_providers"] = [{"text":"impl Unpin for Provider","synthetic":true,"types":[]},{"text":"impl Unpin for ProviderRepository","synthetic":true,"types":[]},{"text":"impl&lt;'a&gt; Unpin for ProviderError&lt;'a&gt;","synthetic":true,"types":[]}];
implementors["particle_services"] = [{"text":"impl Unpin for ParticleAppServices","synthetic":true,"types":[]}];
implementors["server_config"] = [{"text":"impl Unpin for AppServicesConfig","synthetic":true,"types":[]},{"text":"impl Unpin for BootstrapConfig","synthetic":true,"types":[]},{"text":"impl Unpin for FluenceConfig","synthetic":true,"types":[]},{"text":"impl Unpin for NodeConfig","synthetic":true,"types":[]},{"text":"impl Unpin for KademliaConfig","synthetic":true,"types":[]},{"text":"impl Unpin for ListenConfig","synthetic":true,"types":[]},{"text":"impl Unpin for NetworkConfig","synthetic":true,"types":[]},{"text":"impl Unpin for ServicesConfig","synthetic":true,"types":[]}];
implementors["test_utils"] = [{"text":"impl Unpin for ConnectedClient","synthetic":true,"types":[]},{"text":"impl Unpin for Instruction","synthetic":true,"types":[]},{"text":"impl Unpin for CreatedSwarm","synthetic":true,"types":[]},{"text":"impl Unpin for Trust","synthetic":true,"types":[]},{"text":"impl Unpin for SwarmConfig","synthetic":true,"types":[]},{"text":"impl Unpin for CreatedService","synthetic":true,"types":[]}];
implementors["waiting_queues"] = [{"text":"impl Unpin for Enqueued","synthetic":true,"types":[]},{"text":"impl&lt;K, V&gt; Unpin for WaitingQueues&lt;K, V&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;K: Unpin,<br>&nbsp;&nbsp;&nbsp;&nbsp;V: Unpin,&nbsp;</span>","synthetic":true,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()