(function() {var implementors = {};
implementors["aquamarine"] = [{"text":"impl !Sync for AquamarineBackend","synthetic":true,"types":[]},{"text":"impl Sync for AquamarineApi","synthetic":true,"types":[]},{"text":"impl Sync for AwaitedParticle","synthetic":true,"types":[]},{"text":"impl Sync for AwaitedEffects","synthetic":true,"types":[]},{"text":"impl Sync for VmPoolConfig","synthetic":true,"types":[]},{"text":"impl Sync for SendParticle","synthetic":true,"types":[]},{"text":"impl Sync for StepperEffects","synthetic":true,"types":[]},{"text":"impl !Sync for Plumber","synthetic":true,"types":[]}];
implementors["connection_pool"] = [{"text":"impl Sync for ConnectionPoolInlet","synthetic":true,"types":[]},{"text":"impl Sync for ConnectionPoolApi","synthetic":true,"types":[]},{"text":"impl Sync for ConnectionPoolBehaviour","synthetic":true,"types":[]},{"text":"impl Sync for Contact","synthetic":true,"types":[]},{"text":"impl Sync for LifecycleEvent","synthetic":true,"types":[]}];
implementors["fluence_client"] = [{"text":"impl Sync for Transport","synthetic":true,"types":[]},{"text":"impl Sync for Client","synthetic":true,"types":[]},{"text":"impl Sync for ClientCommand","synthetic":true,"types":[]},{"text":"impl Sync for ClientEvent","synthetic":true,"types":[]}];
implementors["fluence_libp2p"] = [{"text":"impl Sync for RandomPeerId","synthetic":true,"types":[]}];
implementors["host_closure"] = [{"text":"impl Sync for Args","synthetic":true,"types":[]},{"text":"impl Sync for ArgsError","synthetic":true,"types":[]},{"text":"impl Sync for JError","synthetic":true,"types":[]}];
implementors["kademlia"] = [{"text":"impl Sync for KademliaApiInlet","synthetic":true,"types":[]},{"text":"impl Sync for KademliaApi","synthetic":true,"types":[]},{"text":"impl Sync for KademliaConfig","synthetic":true,"types":[]},{"text":"impl Sync for Kademlia","synthetic":true,"types":[]},{"text":"impl Sync for KademliaError","synthetic":true,"types":[]}];
implementors["particle_closures"] = [{"text":"impl&lt;C&gt; Sync for HostClosures&lt;C&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;C: Sync,&nbsp;</span>","synthetic":true,"types":[]},{"text":"impl Sync for NodeInfo","synthetic":true,"types":[]}];
implementors["particle_modules"] = [{"text":"impl Sync for Blueprint","synthetic":true,"types":[]},{"text":"impl Sync for ModuleError","synthetic":true,"types":[]}];
implementors["particle_node"] = [{"text":"impl !Sync for Node","synthetic":true,"types":[]},{"text":"impl !Sync for NetworkBehaviour","synthetic":true,"types":[]}];
implementors["particle_protocol"] = [{"text":"impl Sync for CompletionChannel","synthetic":true,"types":[]},{"text":"impl Sync for HandlerMessage","synthetic":true,"types":[]},{"text":"impl Sync for ProtocolConfig","synthetic":true,"types":[]},{"text":"impl Sync for Particle","synthetic":true,"types":[]}];
implementors["particle_providers"] = [{"text":"impl Sync for Provider","synthetic":true,"types":[]},{"text":"impl Sync for ProviderRepository","synthetic":true,"types":[]},{"text":"impl&lt;'a&gt; Sync for ProviderError&lt;'a&gt;","synthetic":true,"types":[]}];
implementors["particle_services"] = [{"text":"impl Sync for ParticleAppServices","synthetic":true,"types":[]}];
implementors["server_config"] = [{"text":"impl Sync for AppServicesConfig","synthetic":true,"types":[]},{"text":"impl Sync for BootstrapConfig","synthetic":true,"types":[]},{"text":"impl Sync for FluenceConfig","synthetic":true,"types":[]},{"text":"impl Sync for NodeConfig","synthetic":true,"types":[]},{"text":"impl Sync for KademliaConfig","synthetic":true,"types":[]},{"text":"impl Sync for ListenConfig","synthetic":true,"types":[]},{"text":"impl Sync for NetworkConfig","synthetic":true,"types":[]},{"text":"impl Sync for ServicesConfig","synthetic":true,"types":[]}];
implementors["test_utils"] = [{"text":"impl Sync for ConnectedClient","synthetic":true,"types":[]},{"text":"impl Sync for Instruction","synthetic":true,"types":[]},{"text":"impl Sync for CreatedSwarm","synthetic":true,"types":[]},{"text":"impl Sync for Trust","synthetic":true,"types":[]},{"text":"impl Sync for SwarmConfig","synthetic":true,"types":[]},{"text":"impl Sync for CreatedService","synthetic":true,"types":[]}];
implementors["waiting_queues"] = [{"text":"impl Sync for Enqueued","synthetic":true,"types":[]},{"text":"impl&lt;K, V&gt; Sync for WaitingQueues&lt;K, V&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;K: Sync,<br>&nbsp;&nbsp;&nbsp;&nbsp;V: Sync,&nbsp;</span>","synthetic":true,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()